<a href="https://colab.research.google.com/github/Dawitkiros/Learn_pytorch/blob/main/learnTensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Importing torch and torch.nn**

In [4]:
from torch import nn
import torch

# Tensor
A tensor is a multi-dimensional array, which is a generalization of vectors and matrices to potentially higher dimensions. In deep learning frameworks like PyTorch, tensors are used to store the data of inputs, outputs, and model parameters.

In [ ]:
# Creating a 2x3 tensor with random values
tensor_example = torch.rand(30, 3)
print(tensor_example)

# **ReLU**
The ReLU (Rectified Linear Unit) function is a non-linear activation function used in neural networks, defined as the positive part of its argument. nn.ReLU() applies the ReLU function element-wise.

In [20]:
import torch.nn as nn

relu = nn.ReLU()
input_tensor = torch.tensor([-1.0, 0.0, -2.0, 2.0])
output_tensor = relu(input_tensor)
print(output_tensor)

leakyrelu = nn.LeakyReLU(0.01)
output_tensor2 = leakyrelu(input_tensor)
print(output_tensor2)


tensor([0., 0., 0., 2.])
tensor([-0.0100,  0.0000, -0.0200,  2.0000])


# **Dropout**

Dropout is a regularization technique to prevent overfitting in neural networks. It randomly zeros some of the elements of the input tensor with probability p during training, which helps to make the model more robust and prevents overfitting on the training data.

In [21]:
dropout = nn.Dropout(p=0.5)  # 50% probability to zero elements
input_tensor = torch.randn(1, 10)  # Random tensor
output_tensor = dropout(input_tensor)
print(output_tensor)

tensor([[-0.0000, -0.0000, -0.0000,  0.0000, -2.5144, -0.0000,  0.8519,  0.7719,
          0.3354,  0.0215]])


# **Linear**

A linear layer (also known as a fully connected layer) applies a linear transformation to the incoming data: y = xA^T + b. It's defined by two parameters: the number of input features (dim_in) and the number of output features (dim_out).

In [23]:
linear_layer = nn.Linear(10, 5)  # 10 input features, 5 output features
input_tensor = torch.rand(1, 10)  # Example input
print(input_tensor)
output_tensor = linear_layer(input_tensor)
print(output_tensor)


tensor([[0.9869, 0.3562, 0.0473, 0.7138, 0.4077, 0.0247, 0.4701, 0.1823, 0.0083,
         0.1875]])
tensor([[-0.0203, -0.2691, -0.0706,  0.2397,  0.1808]],
       grad_fn=<AddmmBackward0>)


Softmax

The Softmax function is used as the activation function for the output layer of a classification network. It turns logits (raw prediction scores) into probabilities by taking the exponentials of each output and then normalizing these values by dividing by the sum of all the exponentials.

In [25]:
softmax = nn.Softmax(dim=1)
input_tensor = torch.randn(1, 3)  # Logits for 3 classes
print(input_tensor)
output_tensor = softmax(input_tensor)
print(output_tensor)


tensor([[-0.4120,  0.1650, -0.2709]])
tensor([[0.2543, 0.4528, 0.2928]])


# **Autograd**
PyTorch's automatic differentiation engine, torch.autograd, automatically computes gradients for tensor operations, which are essential for backpropagation. It allows you to define computational graphs dynamically and compute gradients automatically.

In [30]:
x = torch.randn(3, requires_grad=True)
y = x * 2
y.backward(torch.tensor([1.0, 0.1, 0.01]))
print(x.grad)


tensor([2.0000, 0.2000, 0.0200])


# **Optimizers:**
Located under torch.optim, optimizers update the parameters (weights and biases) of the neural network with the gradients computed during backpropagation. Common optimizers include SGD, Adam, and RMSprop.

In [ ]:
import torch.optim as optim

optimizer = optim.Adam(model.parameters(), lr=0.001)  # model.parameters() contains the parameters to optimize


# **Datasets and DataLoaders**
PyTorch provides these abstractions in torch.utils.data to handle loading the data, making it easier to batch, shuffle, and distribute data across multiple workers.

In [ ]:
from torch.utils.data import Dataset, DataLoader

class CustomDataset(Dataset):
    def __init__(self):
        # Initialize dataset.
        pass
    def __len__(self):
        # Return the size of the dataset.
        return len(self.data)
    def __getitem__(self, idx):
        # Fetch the data item at index `idx`.
        return self.data[idx]

dataset = CustomDataset()
dataloader = DataLoader(dataset, batch_size=4, shuffle=True)


# **Module:**
The nn.Module class is a base class for all neural network modules in PyTorch. It is used to encapsulate parameters, and helpers for moving them between devices, exporting, loading, etc. Defining custom layers or models involves subclassing nn.Module.

In [ ]:
import torch.nn as nn
import torch.nn.functional as F

class CustomModel(nn.Module):
    def __init__(self):
        super(CustomModel, self).__init__()
        self.conv1 = nn.Conv2d(1, 20, 5)
        self.conv2 = nn.Conv2d(20, 20, 5)

    def forward(self, x):
        x = F.relu(self.conv1(x))
        return F.relu(self.conv2(x))


# **Device Management:**
PyTorch provides simple APIs to manage computation devices, allowing easy toggles between CPU and GPU for model training and inference.

In [ ]:
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
tensor = tensor.to(device)
model = model.to(device)

# **Saving and Loading Models:**
PyTorch provides functionality to save and load models, which is crucial for pausing and resuming training, as well as deploying trained models.

In [ ]:
# Saving
torch.save(model.state_dict(), 'model_path.pth')

# Loading
model = TheModelClass(*args, **kwargs)
model.load_state_dict(torch.load('model_path.pth'))
